### ISSUE TITLE
Incomplete .eslintrc for linting

### ISSUE THREAD

**Issue by CL-Jeremy** [edgeimpulse/edge-impulse-cli#45]
As of the latest release, there is a reference to `../.eslintrc.json` on the committer's computer that prevents the new linter from working.

@mmajchrzycki would you please include the content of that file so I could lint my PR at #44 with your latest settings? Thanks in advance.

**Comment by mmajchrzycki** [comment]
@CL-Jeremy the complete [.eslintrc.json](https://github.com/edgeimpulse/edge-impulse-cli/blob/master/.eslintrc.json) has been published.
