### ISSUE TITLE
"$" on Edge Impulse CLI returns invalid statement on Windows device 

### ISSUE THREAD

**Issue by arijitdas123student** [edgeimpulse/edge-impulse-cli#6]
Hi , 
I have been using Edge Impulse CLI on my Ubuntu VM which works greatly. But yesterday I tried out the same on my Windows host machine and it turns out that there are some errors in the guide for installing Edge Impulse CLI. "$" is only used in Linux/Unix based systems. In Windows machines it shows errors. Here's the one below. 
![Screenshot (4)](https://user-images.githubusercontent.com/64097541/99772102-2c80df80-2b30-11eb-9cd5-7732179c2676.png)

Can I do a pull request to change the same in the Readme for this repo for solving the error ?

**Comment by aureleq** [comment]
Hi @arijitdas123student,

The $ is just the symbol of the prompt. It should not be copied to run the CLI commands (either Win or Linux/MacOS).

Aurelien

**Comment by arijitdas123student** [comment]
Hello @aureleq !
Yup I know that $ is the symbol of the terminal...but I wanted to take an instance of what if a person (who isn't familiar with the command line)looks out for using the Edge Impulse CLI and gets error in doing so in a Windows machine.
Hope that you got the point I wanted to mention :)
